// Portal ESLint flat config (Track B).
//
// RATCHET MODE: the pre-existing tree carries lint violations that we do not
// big-bang fix. A checked-in suppressions baseline (eslint-suppressions.json,
// generated by `eslint --suppress-all`) absorbs those; `eslint .` then passes
// as long as no NEW violations are introduced. Touch a legacy file and its
// suppressions shrink automatically — the baseline burns down, never grows.
import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import prettier from 'eslint-config-prettier';

export default tseslint.config(
  {
    // Not source we author or lint.
    ignores: ['dist/**', 'node_modules/**', 'coverage/**'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.{js,jsx,ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.es2022,
      },
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
    },
    plugins: {
      'react-hooks': reactHooks,
      'react-refresh': reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      'react-refresh/only-export-components': [
        'warn',
        { allowConstantExport: true },
      ],
      // strict:false codebase — `any` is pervasive and not this gate's fight.
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  // Test + config files also see Node + Vitest globals.
  {
    files: [
      '**/*.{test,spec}.{js,jsx,ts,tsx}',
      'src/test/**',
      '*.config.{js,ts}',
    ],
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.vitest,
      },
    },
  },
  // Must be last: turn off every rule Prettier owns.
  prettier,
);
